server:
  jwt_secret_key: "1234567890"
  http:
    address: ":8002"
database:
  master:
    host: "db"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "sawitpro"
  slave:
    host: "db"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "sawitpro"